import type { BattleGrowth } from '../battleProgress';
import { creatureArtwork, portrait } from '../portraitUi';

export function battleResultsView(summary: string, growth: BattleGrowth[], requestedIndex: number) {
  const selected=Math.max(0,Math.min(requestedIndex,growth.length-1)),current=growth[selected];
  const leveled=current.levelAfter>current.levelBefore,thresholdAfter=current.levelAfter*12;
  const beforePercent=Math.min(100,current.xpBefore/(current.levelBefore*12)*100),afterPercent=Math.min(100,current.xpAfter/thresholdAfter*100);
  const events=[leveled?`<span class="growth-event level-event">LEVEL UP · Lv.${current.levelAfter}</span>`:'',...current.learnedMoves.map(move=>`<span class="growth-event move-event">${move.kind==='upgraded'?'招式进化':'领悟招式'} · ${move.name}</span>`)].join('');
  const evolution=current.evolution?`<div class="result-evolution"><div>${creatureArtwork(current.monster.species,current.evolution.from)}<small>${current.nameBefore}</small></div><i aria-hidden="true">➜</i><div>${creatureArtwork(current.monster.species,current.evolution.to)}<small>${current.nameAfter}</small></div><b>进化完成</b></div>`:'';
  const html=`<div class="modal-shade result-shade"><section class="battle-result-panel" aria-label="战斗结算"><header class="result-heading"><span>AFTER BATTLE</span><h2>同行成长</h2><p>${summary}</p></header><div class="result-layout"><ol class="growth-party">${growth.map((entry,index)=>`<li><button data-growth-index="${index}" aria-pressed="${index===selected}"><span class="growth-portrait">${portrait(entry.monster)}</span><span class="growth-name"><b>${entry.nameAfter}</b><small>${entry.active?'本场首发':'同行经验'} · +${entry.xpGain} EXP</small></span><span class="growth-level">Lv.${entry.levelAfter}</span>${entry.levelAfter>entry.levelBefore?'<em>UP</em>':''}</button></li>`).join('')}</ol><article class="growth-focus ${leveled?'did-level':''}${current.evolution?' did-evolve':''}" style="--xp-before:${beforePercent}%;--xp-after:${afterPercent}%"><div class="growth-sparkles" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>${evolution||`<div class="growth-creature">${creatureArtwork(current.monster.species,current.monster.form??0)}</div>`}<div class="growth-title"><span>${current.active?'本场首发':'同行伙伴'}</span><h3>${current.nameAfter}</h3><b>Lv.${current.levelBefore}${leveled?` → Lv.${current.levelAfter}`:''}</b></div><div class="growth-xp"><div><span>经验值</span><strong>+${current.xpGain} EXP</strong></div><div class="growth-xp-track"><i></i></div><small>${current.xpAfter} / ${thresholdAfter}</small></div><div class="growth-events">${events||'<span class="growth-event steady-event">经验稳步增长</span>'}</div></article></div><footer class="result-footer"><span>${selected+1} / ${growth.length} · 全队均已获得经验</span><button class="result-next">${selected<growth.length-1?'查看下一位':'继续旅行'} <b>›</b></button></footer></section></div>`;
  return {html,selected};
}
